In [18]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [19]:
df = pd.read_csv("./data/penguins.csv")
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [20]:
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [22]:
df.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [23]:
df = df.dropna() # drop rows with missing values (11 rows)

In [24]:
X = df.drop(columns="species")
y = df["species"]

In [25]:
le_island, le_sex, le = LabelEncoder(), LabelEncoder(), LabelEncoder()

X["island"] = le_island.fit_transform(X["island"]) # Biscoe, Dream, Torgersen -> 0, 1, 2
X["sex"] = le_sex.fit_transform(X["sex"]) # FEMALE, MALE -> 0, 1
y = le.fit_transform(y) # Adelie, Chinstrap, Gentoo -> 0, 1, 2
le.classes_

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
	X, y, test_size=0.3, random_state=42, stratify=y)

In [27]:
X_train

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
268,0,44.9,13.3,213.0,5100.0,0
201,1,49.8,17.3,198.0,3675.0,0
321,0,55.9,17.0,228.0,5600.0,1
341,0,50.4,15.7,222.0,5750.0,1
13,2,38.6,21.2,191.0,3800.0,1
...,...,...,...,...,...,...
14,2,34.6,21.1,198.0,4400.0,1
102,0,37.7,16.0,183.0,3075.0,0
337,0,48.8,16.2,222.0,6000.0,1
306,0,43.4,14.4,218.0,4600.0,0
70,2,33.5,19.0,190.0,3600.0,0

In [28]:
scaler = StandardScaler()
Xtr = scaler.fit_transform(X_train) # fit on TRAIN only
Xte = scaler.transform(X_test)

In [29]:
model = MLPClassifier(hidden_layer_sizes=(20,), max_iter=1000, random_state=42)
model.fit(Xtr, y_train)

MLPClassifier(hidden_layer_sizes=(20,), max_iter=1000, random_state=42)

In [30]:
y_pred_train = model.predict(Xtr)
y_pred_test = model.predict(Xte)

print(f"Train  Acc: {accuracy_score(y_train, y_pred_train):.3f}")
print(f"Test   Acc: {accuracy_score(y_test, y_pred_test):.3f}")
print(classification_report(y_test, y_pred_test, target_names=le.classes_))

Train  Acc: 0.996
Test   Acc: 0.990
              precision    recall  f1-score   support

      Adelie       1.00      0.98      0.99        44
   Chinstrap       0.95      1.00      0.98        20
      Gentoo       1.00      1.00      1.00        36

    accuracy                           0.99       100
   macro avg       0.98      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100

In [31]:
pd.DataFrame(confusion_matrix(y_test, y_pred_test), index=le.classes_, columns=le.classes_) # rows = actual, cols = predicted

           Adelie  Chinstrap  Gentoo
Adelie         43          1       0
Chinstrap       0         20       0
Gentoo          0          0      36

In [34]:
SAVE_CSV = False

submission_df = df.copy()
submission_df["species"] = le.inverse_transform(model.predict(scaler.transform(X))) # 0, 1, 2 -> text
if SAVE_CSV:
	submission_df.to_csv("submission.csv", index=False)

submission_df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE